const fs = require('fs');

const movies = [
  {
    id: '1',
    name: "Big Buck Bunny",
    imageSrc: '/images/movies/bigbuck.jpg',
    imageDescription: 'Animation kids',
    playbackUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    description: "Story of a giant rabbit with a heart bigger than himself. On a sunny day 3 rodents harass him, and he ain't bunny anymore!",
  },
  {
    id: '2',
    name: 'Sintel',
    imageSrc: '/images/movies/sintel.jpg',
    imageDescription: 'Sintel',
    playbackUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    description: "Sintel is an independently produced short film, initiated by the Blender Foundation",
  },
  {
    id: '3',
    name: "Avengers",
    imageSrc: '/images/movies/avengers.jpg',
    imageDescription: 'Iron Man, Captain America, Loki, Thor, Hulk',
    playbackUrl: false,
    description: 'American superhero film based on the Marvel Comics superhero team to save world',
  },
  {
    id: '4',
    name: 'Hereditary',
    imageSrc: '/images/movies/hereditary.jpg',
    imageDescription: 'Tony, Gabriel, Alex',
    playbackUrl: false,
    description: "American supernatural psychological horror drama film based on true life events",
  },
  {
    id: '5',
    name: "Trick's Treat",
    imageSrc: '/images/movies/tricktreat.jpg',
    imageDescription: 'Allien',
    playbackUrl: false,
    description: 'On Halloween, people face their worst nightmares as their paths cross one another',
  },
  {
    id: '6',
    name: 'Jumanji',
    imageSrc: '/images/movies/jumanji.jpg',
    imageDescription: 'Rock, Dwayne Johnson',
    playbackUrl: false,
    description: 'Four teenagers engaged in a magical video game, escape is to finish the game together',
  },
  {
    id: '7',
    name: 'Mission Mangal',
    imageSrc: '/images/movies/mangal.jpg',
    imageDescription: 'Akshay, Sonakshi, Tapsee, Vidya Balan',
    playbackUrl: false,
    description: 'Indian bollywood movie depicting space journey dream of a scientist, releasing on August 15',
  },
  {
    id: '8',
    name: 'Matrix',
    imageSrc: '/images/movies/matrix.jpg',
    imageDescription: 'Morpheus, Trinity, Smith',
    playbackUrl: false,
    description: "Science fiction action movie. Group of heroes who fight desperate war against machine overlords",
  },
  {
    id: '9',
    name: "Star",
    imageSrc: '/images/movies/star.jpg',
    imageDescription: 'Star movie space fiction',
    playbackUrl: false,
    description: 'Saber Raine, an inter-galactic gun-for-hire, must rescue the Aresian Prince and Princess.',
  },
  {
    id: '10',
    name: "Wonder Park",
    imageSrc: '/images/movies/wonder.jpg',
    imageDescription: 'Animation kids',
    playbackUrl: false,
    description: 'Wonder Park is story of amusement park and wildly creative girl named June comes alive',
  }
];

const music = [
  {
    id: '1',
    name: "Album III",
    imageSrc: '/images/music/album.jpg',
    imageDescription: 'Album III',
    playbackUrl: false,
    description: 'Album III Hollywood',
  },
  {
    id: '2',
    name: 'Badshah',
    imageSrc: '/images/music/badshah.jpg',
    imageDescription: 'Badshah',
    playbackUrl: false,
    description: "Badshah punjabi superstar",
  },
  {
    id: '3',
    name: "Diljit",
    imageSrc: '/images/music/diljit.jpg',
    imageDescription: 'Diljit',
    playbackUrl: false,
    description: 'Superstar singer and actor',
  },
  {
    id: '4',
    name: 'Finger Roll',
    imageSrc: '/images/music/fingerroll.jpg',
    imageDescription: 'Finger Roll',
    playbackUrl: false,
    description: "American music series",
  },
  {
    id: '5',
    name: "Latest Hits",
    imageSrc: '/images/music/latest.jpg',
    imageDescription: 'Latest Hits',
    playbackUrl: false,
    description: 'Latest Hits only on 103',
  },
  {
    id: '6',
    name: 'Michael Jackson',
    imageSrc: '/images/music/mj.jpg',
    imageDescription: 'Michael Jackson',
    playbackUrl: false,
    description: 'Legend Moonwalk All time great',
  },
  {
    id: '7',
    name: 'Norah Jane',
    imageSrc: '/images/music/norah.jpg',
    imageDescription: 'Norah Jane',
    playbackUrl: false,
    description: 'Hollywood Music Norah Jane',
  },
  {
    id: '8',
    name: 'Octotune',
    imageSrc: '/images/music/octotune.jpg',
    imageDescription: 'Octotune',
    playbackUrl: false,
    description: "Octotune Hollywood Music",
  },
  {
    id: '9',
    name: "Top Punjabi",
    imageSrc: '/images/music/toppunjabi.jpg',
    imageDescription: 'Top Punjabi',
    playbackUrl: false,
    description: 'Top punjabi hits various artist',
  },
  {
    id: '10',
    name: "Urban Punjabi",
    imageSrc: '/images/music/urbanpunjabi.jpg',
    imageDescription: 'Urban Punjabi',
    playbackUrl: false,
    description: 'Urban punjabi mix hits',
  },
];

const news = [
  {
    id: '1',
    name: "NBC News",
    imageSrc: '/images/news/nbcnews.jpg',
    imageDescription: 'NBC News',
    playbackUrl: false,
    description: 'NBC News channel',
  },
  {
    id: '2',
    name: 'India News',
    imageSrc: '/images/news/indianews.jpg',
    imageDescription: 'India News',
    playbackUrl: false,
    description: "India News Channel",
  },
  {
    id: '3',
    name: "Haryana News",
    imageSrc: '/images/news/haryana.jpg',
    imageDescription: 'Haryana News',
    playbackUrl: false,
    description: 'Best of Haryana News',
  },
  {
    id: '4',
    name: 'Fake News',
    imageSrc: '/images/news/fakenews.jpg',
    imageDescription: 'Fake News',
    playbackUrl: false,
    description: "Fake news for fun",
  },
  {
    id: '5',
    name: "Election",
    imageSrc: '/images/news/election.jpg',
    imageDescription: 'Election News',
    playbackUrl: false,
    description: 'Election News update',
  },
  {
    id: '6',
    name: 'Daily News',
    imageSrc: '/images/news/daily.jpg',
    imageDescription: 'Daily News',
    playbackUrl: false,
    description: 'Daily News update',
  },
  {
    id: '7',
    name: 'Cincinnati News',
    imageSrc: '/images/news/cincinnati.jpg',
    imageDescription: 'Cincinnati News',
    playbackUrl: false,
    description: 'Best of cincinnati news',
  },
  {
    id: '8',
    name: 'Budget News',
    imageSrc: '/images/news/budget.jpg',
    imageDescription: 'Budget News',
    playbackUrl: false,
    description: "Indian Budget News",
  },
  {
    id: '9',
    name: "Breaking News",
    imageSrc: '/images/news/breaking.jpg',
    imageDescription: 'Breaking News',
    playbackUrl: false,
    description: 'Breaking News superfast',
  },
  {
    id: '10',
    name: "Bollywood News",
    imageSrc: '/images/news/bollywood.jpg',
    imageDescription: 'Bollywood News',
    playbackUrl: false,
    description: 'Spicy bollywood news',
  },
];

const sports = [
  {
    id: '1',
    name: "Swimming",
    imageSrc: '/images/sports/swim.jpg',
    imageDescription: 'Swimming',
    playbackUrl: false,
    description: 'Swimming water sports',
  },
  {
    id: '2',
    name: 'Surfing',
    imageSrc: '/images/sports/surfing.jpg',
    imageDescription: 'Surfing',
    playbackUrl: false,
    description: "Surfing high tides",
  },
  {
    id: '3',
    name: "Sports",
    imageSrc: '/images/sports/sports.jpg',
    imageDescription: 'Sports',
    playbackUrl: false,
    description: 'Sports for all',
  },
  {
    id: '4',
    name: 'Running',
    imageSrc: '/images/sports/run.jpg',
    imageDescription: 'Running',
    playbackUrl: false,
    description: "Running for gold",
  },
  {
    id: '5',
    name: "Rugby",
    imageSrc: '/images/sports/rugby.jpg',
    imageDescription: 'Rugby',
    playbackUrl: false,
    description: 'Rugby game of strength',
  },
  {
    id: '6',
    name: 'Kabbadi',
    imageSrc: '/images/sports/kabbadi.jpg',
    imageDescription: 'Kabaddi',
    playbackUrl: false,
    description: 'Kabbadi Premier League',
  },
  {
    id: '7',
    name: 'Cycling',
    imageSrc: '/images/sports/cycle.jpg',
    imageDescription: 'Cycling',
    playbackUrl: false,
    description: 'Cycling for cause',
  },
  {
    id: '8',
    name: 'Cricket',
    imageSrc: '/images/sports/Cricket.jpg',
    imageDescription: 'Cricket',
    playbackUrl: false,
    description: "Indian Cricket team",
  },
  {
    id: '9',
    name: "Basket Ball",
    imageSrc: '/images/sports/basket.jpg',
    imageDescription: 'Basket Ball',
    playbackUrl: false,
    description: 'NBA Basket Ball',
  },
  {
    id: '10',
    name: "Baseball",
    imageSrc: '/images/sports/baseball.jpg',
    imageDescription: 'Baseball',
    playbackUrl: false,
    description: 'Baseball game',
  },
];

try {
  fs.mkdirSync('./data');
} catch (e) {
  if (e.code !== 'EEXIST') throw e;
}
fs.writeFileSync('./data/movies.json', JSON.stringify(movies));
fs.writeFileSync('./data/music.json', JSON.stringify(music));
fs.writeFileSync('./data/news.json', JSON.stringify(news));
fs.writeFileSync('./data/sports.json', JSON.stringify(sports));